Repository randbatch-md/rbmd-gpu, pull requests merged in 2025-06, with the labels that each got.

#53 [new feature]:Add command-line（-j,-h-v）
  examples/01-peo/rbmd.json
  examples/02-water-methane/rbmd.json
  src/application/application.cpp
  src/application/application.h
  src/application/md_application.cpp
  src/application/md_application.h
  src/common/thermo_stats.hpp
  src/common/timing_statistics.hpp
  src/data_manager/include/data_manager.h
  src/data_manager/include/structure_data/full_structure_data.h
  src/data_manager/src/cvff_memory_scheduler.cpp
  src/force/include/cvff.h
  src/force/include/lj.h
  src/force/include/lj_cut_coul_kspace.h
  src/force/src/cvff.cpp
  src/force/src/lj.cpp
  src/force/src/lj_cut_coul_kspace.cpp
  src/parser/command_line.cpp
  src/parser/command_line.h
  src/reader/src/structure_reader.cpp
  src/version.h
Labels: new feature

#56 Add error and warning output formats
  examples/02-water-methane/rbmd.json
  examples/03-metal/Ag/Ag.json
  examples/03-metal/Ag/Ag_4k_v.data
  examples/03-metal/Ag/Ag_u3.eam
  examples/03-metal/Au/Au.json
  examples/03-metal/Au/Au_4k_v.data
  examples/03-metal/Au/Au_u3.eam
  examples/03-metal/Cu/Cu.json
  examples/03-metal/Cu/Cu10_v.data
  examples/03-metal/Cu/Cu_u3.eam
  src/application/md_application.cpp
  src/common/rbmd_define.h
  src/common/thermo_stats.hpp
  src/data_manager/include/force_field/cvff_force_field_data.h
  src/data_manager/include/force_field/eam_force_field_data.h
  src/data_manager/include/force_field/force_field_data.h
  src/data_manager/include/force_field/lj_force_field_data.h
  src/data_manager/include/model/device_data.h
  src/data_manager/src/cvff_memory_scheduler.cpp
  src/data_manager/src/eam_memory_scheduler.cpp
  src/data_manager/src/lj_memory_scheduler.cpp
  src/data_manager/src/memory_scheduler.cpp
  src/force/include/cvff.h
  src/force/include/eam.h
  src/force/include/lj.h
  src/force/include/lj_cut_coul_kspace.h
  src/force/src/cvff.cpp
  src/force/src/cvff_op/rocm/cvff_op.hip.cu
  src/force/src/eam.cpp
  src/force/src/eam_op/eam_op.cpp
  src/force/src/eam_op/eam_op.h
  src/force/src/eam_op/rocm/eam_op.hip.cu
  src/force/src/force_op/force_op.cpp
  src/force/src/force_op/force_op.h
  src/force/src/force_op/rocm/force_op.hip.cu
  src/force/src/lj.cpp
  src/force/src/lj_cut_coul_kspace.cpp
  src/force/src/lj_op/lj_op.h
  src/force/src/lj_op/rocm/lj_op.hip.cu
  src/neighbor_list/src/linked_cell/linked_cell.cpp
  src/parser/command_line.cpp
  src/reader/src/atomic_reader.cpp
  src/reader/src/structure_reader.cpp
  src/simulate_pipeline/src/controller/energy_stable_controller/energy_stable_scheme_controller.cpp
  src/simulate_pipeline/src/controller/pressure_controller/berendsen_pressure_controller.cpp
  src/simulate_pipeline/src/controller/pressure_controller/berendsen_pressure_controller.h
  src/simulate_pipeline/src/controller/pressure_controller/nose_hoover_controller.cpp
  src/simulate_pipeline/src/controller/pressure_controller/nose_hoover_controller.h
  src/simulate_pipeline/src/controller/temperature_controller/berendsen_controller.cpp
  src/simulate_pipeline/src/controller/temperature_controller/berendsen_controller.h
  src/simulate_pipeline/src/controller/temperature_controller/langevin_controller.cpp
  src/simulate_pipeline/src/controller/temperature_controller/langevin_controller.h
  src/simulate_pipeline/src/controller/temperature_controller/rescale_controller.cpp
  src/simulate_pipeline/src/controller/temperature_controller/rescale_controller.h
  src/simulate_pipeline/src/controller/temperature_controller/temperature_controller.h
  src/simulate_pipeline/src/npt_ensemble.cpp
  src/simulate_pipeline/src/nve_ensemble.cpp
  src/simulate_pipeline/src/nvt_ensemble.cpp
Labels: enhancement

#58 Dev fixreader pr
  src/common/types.h
  src/data_manager/include/force_field/lj_force_field_data.h
  src/data_manager/include/model/structure_info_data.h
  src/data_manager/include/structure_data/structure_data.h
  src/data_manager/src/lj_memory_scheduler.cpp
  src/neighbor_list/include/neighbor_list_builder/base_neighbor_list_builder.h
  src/neighbor_list/include/neighbor_list_builder/full_neighbor_list_builder.h
  src/neighbor_list/src/neighbor_list_builder/full_neighbor_list_builder.cpp
  src/reader/src/structure_reader.cpp
Labels: bug, new feature
